apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
     labels:
       app: {{ .Values.selector.app }}
    spec:
      containers:
        - image: {{ .Values.image.prefix }}/{{ .Values.image.name }}:{{ .Values.image.tag }} 
          imagePullPolicy: Always 
          name: {{ .Values.selector.app }} 
          ports:
            - containerPort: {{ .Values.image.port }}