apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          args:
            - "--default-authentication-plugin=mysql_native_password"
          name: {{ .Values.selector.app }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapRef.name }}
            - secretRef:
                name: {{ .Values.secretRef.name }}
          ports:
            - containerPort: {{ .Values.image.port }}
              name: {{ .Values.selector.app }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.claim }}