replicaCount: 2

selector:
  app: users

configMapRef:
  name: mysql-config

secretRef:
  name: mysql-secret

image:
  prefix: vladshalavinskiy
  name: users
  tag: lab2
  port: 3000

service:
  ports:
    port: 3001
    containerPort: 3000

ingress:
  path: /api/users